import type { PresetConfig } from "./preset-schema";

export const zohranClassic: PresetConfig = {
  id: "zohran-classic",
  name: "Zohran Classic",
  description: "Mountain road backdrop with gold hue, rose-heart decor, and psychedelic text",
  defaultProps: {
    width: 1080,
    height: 1920,
    fps: 30,
    durationInFrames: 300,
    background: {
      type: "image",
      source: "/assets/ladakh-highway.jpg",
      animation: "slow-zoom",
    },
    hue: {
      enabled: true,
      color: "#FFD700",
      opacity: 0.55,
      animation: "cycle",
    },
    head: {
      imageUrl: "/assets/heads/zohran.png",
      position: { x: 50, y: 45 },
      scale: 0.85,
      enterAtFrame: 45,
      animation: "spiral-multiply",
      animationConfig: {
        spiralCount: 6,
        orbitRadius: 450,
        orbitSpeed: 0.5,
        copyScale: 0.5,
      },
      flowerReveal: { enabled: true, type: "sunflower", videoSource: "/assets/sunflower-bloom.mp4", enterAtFrame: 15 },
    },
    decorativeElements: [
      {
        type: "image",
        source: "/assets/rose.png",
        position: { x: 50, y: 45 },
        scale: 3.0,
        enterAtFrame: 0,
        exitAtFrame: 45,
        animation: "rose-heart",
      },
      { type: "image", source: "/assets/rose.png", position: { x: 15, y: 10 }, scale: 0.8, enterAtFrame: 50, animation: "pulse" },
      { type: "image", source: "/assets/rose.png", position: { x: 85, y: 15 }, scale: 0.8, enterAtFrame: 55, animation: "pulse" },
      { type: "image", source: "/assets/rose.png", position: { x: 10, y: 85 }, scale: 0.8, enterAtFrame: 60, animation: "pulse" },
      { type: "image", source: "/assets/rose.png", position: { x: 90, y: 80 }, scale: 0.8, enterAtFrame: 65, animation: "pulse" },
    ],
    textSlots: [
      {
        id: "word-0",
        text: "EID",
        position: { x: 50, y: 22 },
        fontFamily: "psychedelic",
        fontSize: 120,
        color: "#FFFFFF",
        stroke: "#FFD700",
        shadow: true,
        animation: "rise-up",
        enterAtFrame: 50,
        group: "greeting",
      },
      {
        id: "word-1",
        text: "MUBARAK",
        position: { x: 50, y: 68 },
        fontFamily: "psychedelic",
        fontSize: 100,
        color: "#FFFFFF",
        stroke: "#FFD700",
        shadow: true,
        animation: "rise-up",
        enterAtFrame: 55,
        group: "greeting",
      },
    ],
    audio: { trackUrl: "", volume: 0.8 },
  },
};
